"""Thingiverse constants.
"""

MAX_N_FACES=500000

LICENSE_IDS = {
    "Creative Commons - Attribution" : "cc",
    "Creative Commons - Attribution - Share Alike" : "ccsa",
    "Creative Commons - Attribution - No Derivatives" : "ccnd",
    "Creative Commons - Attribution - Non-Commercial" : "ccnc",
    "Creative Commons - Attribution - Non-Commercial - Share Alike" : "ccncsa",
    "Creative Commons - Attribution - Non-Commercial - No Derivatives" : "ccncnd",
    "Creative Commons - Public Domain Dedication" : "pd0",
    "GNU - GPL" : "gpl",
    "GNU - LGPL" : "lgpl",
    "BSD License" : "bsd",
    "All Rights Reserved" : "none",
    "Nokia" : "nokia",
    "Public Domain" : "public",
}

CATEGORY_IDS = {
    "3d-printing" : "73",
    "art" : "63",
    "fashion" : "64",
    "gadgets" : "65",
    "hobby" : "66",
    "household" : "67",
    "learning" : "69",
    "models" : "70",
    "tools" : "71",
    "toys-and-games" : "72",
    "2d-art" : "144",
    "art-tools" : "75",
    "coins-and-badges" : "143",
    "interactive-art" : "78",
    "math-art" : "79",
    "scans-and-replicas" : "145",
    "sculptures" : "80",
    "signs-and-logos" : "76",
    "accessories" : "81",
    "bracelets" : "82",
    "costume" : "142",
    "earrings" : "139",
    "glasses" : "83",
    "jewelry" : "84",
    "keychains" : "130",
    "rings" : "85",
    "audio" : "141",
    "camera" : "86",
    "computer" : "87",
    "mobile-phone" : "88",
    "tablet" : "90",
    "videogames" : "91",
    "automotive" : "155",
    "diy" : "93",
    "electronics" : "92",
    "music" : "94",
    "rc-vehicles" : "95",
    "robotics" : "96",
    "sport-and-outdoors" : "140",
    "bathroom" : "147",
    "containers" : "146",
    "decor" : "97",
    "household-supplies" : "99",
    "kitchen-and-dining" : "100",
    "office" : "101",
    "organization" : "102",
    "outdoor-and-garden" : "98",
    "pets" : "103",
    "replacement-parts" : "153",
    "biology" : "106",
    "engineering" : "104",
    "math" : "105",
    "physics-and-astronomy" : "148",
    "animals" : "107",
    "buildings-and-structures" : "108",
    "creatures" : "109",
    "food-and-drink" : "110",
    "model-furniture" : "111",
    "model-robots" : "115",
    "people" : "112",
    "props" : "114",
    "vehicles" : "116",
    "hand-tools" : "118",
    "machine-tools" : "117",
    "parts" : "119",
    "tool-holders-and-boxes" : "120",
    "chess" : "151",
    "construction-toys" : "121",
    "dice" : "122",
    "games" : "123",
    "mechanical-toys" : "124",
    "playsets" : "113",
    "puzzles" : "125",
    "toy-and-game-accessories" : "149",
    "3d-printer-accessories" : "127",
    "3d-printer-extruders" : "152",
    "3d-printer-parts" : "128",
    "3d-printers" : "126",
    "3d-printing-tests" : "129"
}

